Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/lecture-python/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/share/miniconda3/envs/lecture-python/lib/python3.8/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda3/envs/lecture-python/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/share/miniconda3/envs/lecture-python/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/share/miniconda3/envs/lecture-python/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/share/miniconda3/envs/lecture-python/lib/python3.8/site-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda3/envs/lecture-python/lib/python3.8/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/share/miniconda3/envs/lecture-python/lib/python3.8/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
grid = og.grid

v_init = v_star(grid, Î±, og.Î², og.Î¼)    # Start at the solution
v_greedy, v = T(v_init, og)             # Apply T once

fig, ax = plt.subplots()
ax.set_ylim(-35, -24)
ax.plot(grid, v, lw=2, alpha=0.6, label='$Tv^*$')
ax.plot(grid, v_init, lw=2, alpha=0.6, label='$v^*$')
ax.legend()
plt.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-6-853f5d71e07c>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0mgrid[0m [0;34m=[0m [0mog[0m[0;34m.[0m[0mgrid[0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0;34m[0m[0m
[0;32m----> 3[0;31m [0mv_init[0m [0;34m=[0m [0mv_star[0m[0;34m([0m[0mgrid[0m[0;34m,[0m [0mÎ±[0m[0;34m,[0m [0mog[0m[0;34m.[0m[0mÎ²[0m[0;34m,[0m [0mog[0m[0;34m.[0m[0mÎ¼[0m[0;34m)[0m    [0;31m# Start at the solution[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      4[0m [0mv_greedy[0m[0;34m,[0m [0mv[0m [0;34m=[0m [0mT[0m[0;34m([0m[0mv_init[0m[0;34m,[0m [0mog[0m[0;34m)[0m             [0;31m# Apply T once[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0;34m[0m[0m

[0;31mNameError[0m: name 'v_star' is not defined
NameError: name 'v_star' is not defined

